using Unity.AI.Navigation;
using UnityEngine;

namespace Tycoon.Core
{
    /// <summary>
    /// Bakes the level's navigation mesh when the game starts.
    ///
    /// Baked at runtime rather than stored as an asset because the level itself is generated by
    /// script: a baked NavMeshData asset would have to be regenerated and committed every time
    /// the layout moved by a metre, and would silently go stale if anyone forgot.
    ///
    /// A farm-sized level bakes in a few milliseconds, and it runs before the first frame, so
    /// there is nothing to see. Buildings that appear later - a coop that gets unlocked - do not
    /// need a rebake: they carry carving NavMeshObstacles that cut their own hole.
    /// </summary>
    [RequireComponent(typeof(NavMeshSurface))]
    [DefaultExecutionOrder(-5000)]
    public class NavigationBaker : MonoBehaviour
    {
        private void Awake()
        {
            var surface = GetComponent<NavMeshSurface>();
            if (surface == null) return;

            surface.BuildNavMesh();
        }
    }
}
