using Tycoon.Stations;
using UnityEngine;
using UnityEngine.UI;

namespace Tycoon.UI
{
    /// <summary>
    /// The painted square on the ground that says "stand here".
    ///
    /// This is the main way the game talks to the player, so it has to do three things at a
    /// glance: say what the action is, make it obvious when you are actually inside it, and
    /// show how the action is going.
    ///
    /// Built as a world-space canvas laid flat rather than a textured quad, because the canvas
    /// route reuses the sprites and fonts generated by <see cref="UIFactory"/>, which are known
    /// to survive the Web build. Materials created from scratch at runtime render magenta in a
    /// URP player, which cost an hour to diagnose once already.
    /// </summary>
    public class InteractionSquare : MonoBehaviour
    {
        [Header("Source")]
        public StationBase station;

        [Header("Look")]
        public Vector2 size = new Vector2(2f, 2f);
        public Color color = new Color(0.35f, 0.8f, 1f);

        [Tooltip("Optional. When empty the square shows only its label.")]
        public Sprite icon;

        [Tooltip("Height above the ground. Just enough to avoid z-fighting.")]
        public float lift = 0.045f;

        [Header("Motion")]
        [Tooltip("How far the square swells while idle, inviting the player over.")]
        [Range(0f, 0.15f)] public float idlePulse = 0.045f;

        public float pulseSpeed = 2.1f;

        private RectTransform _root;
        private Image _border;
        private Image _backdrop;
        private Image _fill;
        private Image _iconImage;
        private Text _label;
        private RectTransform _labelRoot;

        private float _scale = 1f;

        // ---- cost control -------------------------------------------------------------
        // Writing to a Graphic's colour, or to an Image's fillAmount, marks its canvas dirty
        // and rebuilds the mesh. A square that nobody is standing in has constant colours, so
        // the last applied values are remembered and identical writes are skipped. An idle
        // square then costs a handful of float comparisons instead of a canvas rebuild.
        private Color _lastBorder, _lastBackdrop, _lastFill, _lastLabelColor;
        private float _lastFillAmount = -1f;
        private bool _hasAppliedColors;

        /// <summary>Seconds between off-screen checks. Cheap, but there is no need to be exact.</summary>
        private const float VisibilityInterval = 0.2f;

        /// <summary>
        /// Seconds between label refreshes. Every StatusText override builds a new string, so
        /// at frame rate the squares alone allocated a couple of thousand strings a second -
        /// which on WebGL is paid back as collection hitches. Six times a second still reads
        /// as live for a counter that changes at most a few times a second anyway.
        /// </summary>
        private const float LabelInterval = 0.16f;

        private float _visibilityTimer;
        private float _labelTimer;
        private bool _visible = true;

        private void Awake()
        {
            Build();

            // Stagger the timers so thirty-five squares do not all do their off-screen test and
            // rebuild their labels on the same frame, which would show up as a regular stutter.
            _visibilityTimer = Random.value * VisibilityInterval;
            _labelTimer = Random.value * LabelInterval;
        }

        /// <summary>
        /// Called by the level builder. Deliberately stores data only and builds nothing:
        /// geometry created at edit time gets serialised into the scene, and then Awake builds
        /// a second copy at runtime. The saved one is left orphaned with nothing updating it,
        /// which shows up as a plain white rectangle sitting on top of the real square.
        /// </summary>
        public void Configure(StationBase owner, Vector2 squareSize, Color squareColor)
        {
            station = owner;
            size = squareSize;
            color = squareColor;
        }

        private void Build()
        {
            if (_root != null) return;

            // Clear any leftovers rather than stacking another set on top.
            var stale = transform.Find("~Square");
            if (stale != null) DestroyImmediate(stale.gameObject);
            var staleLabel = transform.Find("~SquareLabel");
            if (staleLabel != null) DestroyImmediate(staleLabel.gameObject);

            var go = new GameObject("~Square");
            // Never serialised into the scene - see Configure.
            go.hideFlags = HideFlags.DontSave;
            go.transform.SetParent(transform, false);
            // Flat on the ground. The parent already carries the level's 45 degree yaw, so the
            // square lines up with the level grid rather than with world axes.
            go.transform.localRotation = Quaternion.Euler(90f, 0f, 0f);

            var canvas = go.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.WorldSpace;

            _root = (RectTransform)go.transform;

            _border = UIFactory.CreatePanel("Border", _root, Color.white);
            Stretch(_border.rectTransform, 0f);

            _backdrop = UIFactory.CreatePanel("Backdrop", _root, Color.white);
            Stretch(_backdrop.rectTransform, 9f);

            _fill = UIFactory.CreatePanel("Fill", _root, Color.white);
            Stretch(_fill.rectTransform, 9f);
            _fill.type = Image.Type.Filled;
            _fill.fillMethod = Image.FillMethod.Horizontal;
            _fill.fillOrigin = (int)Image.OriginHorizontal.Left;
            _fill.fillAmount = 0f;

            var iconGo = UIFactory.CreateRect("Icon", _root);
            _iconImage = iconGo.gameObject.AddComponent<Image>();
            _iconImage.raycastTarget = false;
            iconGo.anchorMin = iconGo.anchorMax = new Vector2(0.5f, 0.68f);
            iconGo.pivot = new Vector2(0.5f, 0.5f);
            iconGo.sizeDelta = new Vector2(56f, 56f);
            _iconImage.enabled = false;

            // The label lives on its own upright canvas, not flat on the ground with the rest
            // of the square. Once the camera is turned off the level grid, ground-flat text is
            // both tilted and foreshortened, which makes the one thing the player most needs to
            // read the hardest thing to read.
            var labelGo = new GameObject("~SquareLabel");
            labelGo.hideFlags = HideFlags.DontSave;
            labelGo.transform.SetParent(transform, false);

            var labelCanvas = labelGo.AddComponent<Canvas>();
            labelCanvas.renderMode = RenderMode.WorldSpace;

            _labelRoot = (RectTransform)labelGo.transform;
            _labelRoot.sizeDelta = new Vector2(340f, 90f);
            _labelRoot.localScale = Vector3.one * 0.01f;
            _labelRoot.localPosition = Vector3.up * 0.75f;

            _label = UIFactory.CreateText("Label", _labelRoot, "", 52);
            _label.fontStyle = FontStyle.Bold;
            Stretch(_label.rectTransform, 0f);

            Rebuild();
        }

        private static void Stretch(RectTransform rect, float inset)
        {
            rect.anchorMin = Vector2.zero;
            rect.anchorMax = Vector2.one;
            rect.offsetMin = new Vector2(inset, inset);
            rect.offsetMax = new Vector2(-inset, -inset);
        }

        /// <summary>Applies size, colour and label. Cheap enough to call whenever they change.</summary>
        private void Rebuild()
        {
            if (_root == null) return;

            // 100 canvas pixels per world unit, then scaled back down, so `size` is in metres.
            _root.sizeDelta = size * 100f;
            _root.localScale = Vector3.one * 0.01f;
            _root.localPosition = Vector3.up * lift;

            if (_iconImage != null)
            {
                _iconImage.sprite = icon;
                _iconImage.enabled = icon != null;
            }

            if (_label != null)
            {
                _label.text = station != null ? station.StatusText : "";
                // With an icon the text sits below it; without, it centres.
                _label.alignment = icon != null ? TextAnchor.LowerCenter : TextAnchor.MiddleCenter;
            }
        }

        private void LateUpdate()
        {
            if (_labelRoot == null || !_visible) return;

            var camera = WorldUi.Camera;
            if (camera != null) _labelRoot.rotation = camera.transform.rotation;
        }

        /// <summary>
        /// Turns the whole square off when it is off screen. Disabling the canvas objects takes
        /// them out of the UI rebuild and render passes entirely, which is the single biggest
        /// saving available: a full farm has thirty-five squares and the camera shows about six.
        /// </summary>
        private void SetVisible(bool visible)
        {
            if (_visible == visible) return;
            _visible = visible;

            if (_root != null) _root.gameObject.SetActive(visible);
            if (_labelRoot != null) _labelRoot.gameObject.SetActive(visible);

            // Coming back on screen, re-apply everything: the station may have changed
            // completely while it was hidden.
            if (visible)
            {
                _hasAppliedColors = false;
                _lastFillAmount = -1f;
                _labelTimer = 0f;
            }
        }

        private void Update()
        {
            if (_root == null || station == null) return;

            _visibilityTimer -= Time.deltaTime;
            if (_visibilityTimer <= 0f)
            {
                _visibilityTimer = VisibilityInterval;
                SetVisible(WorldUi.IsVisible(transform.position));
            }

            if (!_visible) return;

            bool occupied = station.IsOccupied;
            bool usable = station.IsOperational;
            float progress = station.Progress01;

            // Idle squares breathe gently to draw the eye. A square being used holds still,
            // because the progress fill is the thing the player should be reading.
            float targetScale = 1f;
            if (!occupied && usable)
                targetScale = 1f + Mathf.Sin(Time.time * pulseSpeed) * 0.5f * idlePulse + idlePulse * 0.5f;
            else if (occupied)
                targetScale = 1.03f;

            float previous = _scale;
            _scale = Mathf.Lerp(_scale, targetScale, Time.deltaTime * 9f);
            // Moving the canvas root re-transforms every child, so a square that has settled at
            // its resting size (an unusable one, or one being stood in) stops writing.
            if (Mathf.Abs(_scale - previous) > 0.0002f)
                _root.localScale = Vector3.one * 0.01f * _scale;

            Color baseColor = usable ? color : Color.Lerp(color, new Color(0.55f, 0.57f, 0.6f), 0.45f);

            // Border: thin and soft when idle, bright and solid the moment you step in. This is
            // the single clearest signal that the player is standing in the right place.
            Apply(_border, ref _lastBorder, new Color(
                Mathf.Lerp(baseColor.r, 1f, occupied ? 0.55f : 0.15f),
                Mathf.Lerp(baseColor.g, 1f, occupied ? 0.55f : 0.15f),
                Mathf.Lerp(baseColor.b, 1f, occupied ? 0.55f : 0.15f),
                occupied ? 0.95f : 0.45f));

            Apply(_backdrop, ref _lastBackdrop,
                new Color(baseColor.r, baseColor.g, baseColor.b, occupied ? 0.55f : 0.34f));

            Apply(_fill, ref _lastFill, new Color(
                Mathf.Lerp(baseColor.r, 1f, 0.35f),
                Mathf.Lerp(baseColor.g, 1f, 0.35f),
                Mathf.Lerp(baseColor.b, 1f, 0.35f),
                0.75f));

            Apply(_label, ref _lastLabelColor, new Color(1f, 1f, 1f, usable ? 0.95f : 0.5f));

            _hasAppliedColors = true;

            // Changing fillAmount regenerates the image's geometry, so the eased value is
            // snapped to a step first. Forty steps is finer than the ring is wide on a phone,
            // and it means a ring that has finished moving stops costing anything at all.
            float eased = Mathf.Lerp(_lastFillAmount < 0f ? progress : _lastFillAmount,
                progress, Time.deltaTime * 12f);
            float stepped = Mathf.Round(eased * 40f) / 40f;
            if (!Mathf.Approximately(stepped, _lastFillAmount))
            {
                _lastFillAmount = stepped;
                _fill.fillAmount = stepped;
            }

            _labelTimer -= Time.deltaTime;
            if (_labelTimer <= 0f)
            {
                _labelTimer = LabelInterval;
                string wanted = station.StatusText;
                if (_label.text != wanted) _label.text = wanted;
            }
        }

        /// <summary>
        /// Writes a colour only when it has actually changed. Assigning the same colour still
        /// dirties the graphic and rebuilds its canvas, and an idle square assigns the same four
        /// colours every single frame.
        /// </summary>
        private void Apply(Graphic graphic, ref Color last, Color wanted)
        {
            if (graphic == null) return;
            if (_hasAppliedColors && Same(last, wanted)) return;

            last = wanted;
            graphic.color = wanted;
        }

        /// <summary>Equal to well below one step of an eight-bit colour channel.</summary>
        private static bool Same(Color a, Color b) =>
            Mathf.Abs(a.r - b.r) < 0.002f && Mathf.Abs(a.g - b.g) < 0.002f &&
            Mathf.Abs(a.b - b.b) < 0.002f && Mathf.Abs(a.a - b.a) < 0.002f;
    }
}
