using Tycoon.Config;
using Tycoon.Stations;
using UnityEngine;
using UnityEngine.UI;

namespace Tycoon.UI
{
    /// <summary>
    /// The painted square on the ground that says "stand here".
    ///
    /// This is the main way the game talks to the player, so it has to do three things at a
    /// glance: say what the action is, make it obvious when you are actually inside it, and
    /// show how the action is going.
    ///
    /// Everything lives on ONE card lying on the ground - icon, label, value and progress. The
    /// label used to sit on a second canvas floating three quarters of a metre up, 3.4 metres
    /// wide whatever the square underneath it was, which is how text ended up hanging off the
    /// side of small squares and disappearing behind buildings. Now nothing can leave the card,
    /// so nothing can end up anywhere it should not be.
    ///
    /// Built as a world-space canvas rather than a textured quad, because the canvas route
    /// reuses the sprites and fonts generated by <see cref="UIFactory"/>, which are known to
    /// survive the Web build. Materials created from scratch at runtime render magenta in a URP
    /// player, which cost an hour to diagnose once already.
    /// </summary>
    public class InteractionSquare : MonoBehaviour
    {
        [Header("Source")]
        public StationBase station;

        [Header("Look")]
        public Vector2 size = new Vector2(2f, 2f);
        public Color color = new Color(0.35f, 0.8f, 1f);

        [Tooltip("Height above the ground. Enough to clear the ground detail a square may be " +
                 "painted over - a field's soil and furrows, a pen's dirt - without floating.")]
        public float lift = 0.09f;

        [Header("Motion")]
        [Tooltip("How far the square swells while idle, inviting the player over.")]
        [Range(0f, 0.15f)] public float idlePulse = 0.045f;

        public float pulseSpeed = 2.1f;

        /// <summary>
        /// The card never shrinks below this, however small the trigger is.
        ///
        /// A 1.8 m repair square would otherwise leave about eleven screen pixels for a line of
        /// text once the camera's tilt has squashed it. Chosen against the tightest pair on the
        /// farm - a coop's fix and buy squares, 3.2 m apart - so two cards laid at this size
        /// still do not touch once turned to face the camera.
        /// </summary>
        private static readonly Vector2 MinCard = new Vector2(2.5f, 2.1f);

        /// <summary>
        /// And never grows beyond this, however big the trigger is.
        ///
        /// A corn field's trigger is 5.5 x 3.5 m; a card that size would be a billboard lying in
        /// a field. The crops already show how far the field reaches, so the card only has to be
        /// big enough to read.
        /// </summary>
        private static readonly Vector2 MaxCard = new Vector2(3.4f, 2.4f);

        private RectTransform _root;
        private Image[] _edges;
        private Image _backdrop;
        private Image _progressTrack;
        private Image _progressFill;
        private Image _iconImage;
        private Text _label;
        private Text _value;

        private float _scale = 1f;
        private float _appliedYaw = float.NaN;

        // ---- cost control -------------------------------------------------------------
        // Writing to a Graphic's colour, or to an Image's fillAmount, marks its canvas dirty
        // and rebuilds the mesh. A square that nobody is standing in has constant colours, so
        // the last applied values are remembered and identical writes are skipped. An idle
        // square then costs a handful of float comparisons instead of a canvas rebuild.
        private Color _lastBorder, _lastBackdrop, _lastFill, _lastLabelColor, _lastValueColor;
        private Color _lastTrackColor, _lastIconColor;
        private float _lastFillAmount = -1f;
        private bool _hasAppliedColors;

        private string _lastRawLabel;
        private Sprite _lastIconSprite;

        /// <summary>Seconds between off-screen checks. Cheap, but there is no need to be exact.</summary>
        private const float VisibilityInterval = 0.2f;

        /// <summary>
        /// Seconds between label refreshes. Every status override builds a new string, so at
        /// frame rate the squares alone allocated a couple of thousand strings a second - which
        /// on WebGL is paid back as collection hitches. Six times a second still reads as live
        /// for a counter that changes at most a few times a second anyway.
        /// </summary>
        private const float LabelInterval = 0.16f;

        private float _visibilityTimer;
        private float _labelTimer;
        private bool _visible = true;

        private void Awake()
        {
            Build();

            // Stagger the timers so thirty-five squares do not all do their off-screen test and
            // rebuild their labels on the same frame, which would show up as a regular stutter.
            _visibilityTimer = Random.value * VisibilityInterval;
            _labelTimer = Random.value * LabelInterval;
        }

        /// <summary>
        /// Called by the level builder. Deliberately stores data only and builds nothing:
        /// geometry created at edit time gets serialised into the scene, and then Awake builds
        /// a second copy at runtime. The saved one is left orphaned with nothing updating it,
        /// which shows up as a plain white rectangle sitting on top of the real square.
        /// </summary>
        public void Configure(StationBase owner, Vector2 squareSize, Color squareColor)
        {
            station = owner;
            size = squareSize;
            color = squareColor;
        }

        /// <summary>The card's footprint: the trigger's, held inside readable limits.</summary>
        private Vector2 CardSize => new Vector2(
            Mathf.Clamp(size.x, MinCard.x, MaxCard.x),
            Mathf.Clamp(size.y, MinCard.y, MaxCard.y));

        private void Build()
        {
            if (_root != null) return;

            // Clear any leftovers rather than stacking another set on top. "~SquareLabel" was
            // the old detached label canvas; scenes built before this change still carry one.
            DestroyChild("~Square");
            DestroyChild("~SquareLabel");

            var go = new GameObject("~Square");
            // Never serialised into the scene - see Configure.
            go.hideFlags = HideFlags.DontSave;
            go.transform.SetParent(transform, false);

            var canvas = go.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.WorldSpace;

            _root = (RectTransform)go.transform;

            Vector2 card = CardSize;
            float w = card.x * 100f;
            float h = card.y * 100f;

            // Proportions of the card's height, so every size of card is laid out the same.
            float pad = h * 0.06f;
            float barHeight = h * 0.07f;
            float iconHeight = h * 0.26f;
            float labelHeight = h * 0.34f;
            float valueHeight = h * 0.20f;

            // A faint wash rather than a panel. The square is meant to look like paint on the
            // ground, so the grass has to show through it.
            _backdrop = UIFactory.CreatePanel("Backdrop", _root, Color.white);
            Stretch(_backdrop.rectTransform, h * 0.03f);

            // Marked out with a dashed, round-cornered outline, the way a loading bay is.
            var frameGo = UIFactory.CreateRect("Frame", _root);
            Stretch(frameGo, 0f);
            var frame = frameGo.gameObject.AddComponent<Image>();
            frame.sprite = UIFactory.DashedFrame(Mathf.RoundToInt(w), Mathf.RoundToInt(h));
            frame.raycastTarget = false;
            _edges = new[] { frame };

            // Stacked from the far edge inwards: what it does, the icon, how it is going,
            // progress. Laid out vertically rather than icon-beside-text because the card is
            // only ever about 110 screen pixels across - putting the text in a side column
            // would leave it too narrow for a word like COLLECT without shrinking it to nothing.
            //
            // The word goes at the far edge deliberately. The camera looks across the farm from
            // one side, so a building always spills over the ground *behind* it - and a square
            // tucked against a coop loses its near edge under the roof. Whatever else gets
            // clipped, the word survives.
            float cursor = h * 0.5f - pad;

            _label = TextBlock("Label", w - pad * 2f, labelHeight, ref cursor, Mathf.RoundToInt(labelHeight * 0.82f));
            _label.fontStyle = FontStyle.Bold;
            // Wrap rather than run off the side. The rect is a hard ceiling of two lines.
            _label.horizontalOverflow = HorizontalWrapMode.Wrap;
            _label.verticalOverflow = VerticalWrapMode.Truncate;
            _label.resizeTextForBestFit = true;
            _label.resizeTextMinSize = Mathf.RoundToInt(labelHeight * 0.34f);
            _label.resizeTextMaxSize = Mathf.RoundToInt(labelHeight * 0.82f);

            _iconImage = Block("Icon", w - pad * 2f, iconHeight, ref cursor)
                .gameObject.AddComponent<Image>();
            _iconImage.raycastTarget = false;
            // Icons are square; never let a wide card stretch an egg sideways.
            _iconImage.preserveAspect = true;
            _iconImage.enabled = false;

            _value = TextBlock("Value", w - pad * 2f, valueHeight, ref cursor, Mathf.RoundToInt(valueHeight * 0.85f));
            _value.fontStyle = FontStyle.Bold;

            // Progress sits along the bottom edge as a bar rather than sweeping across the whole
            // card, so a half-filled ring can never wash out the text sitting on top of it.
            _progressTrack = UIFactory.CreatePanel("ProgressTrack", _root, Color.white);
            var track = _progressTrack.rectTransform;
            track.anchorMin = track.anchorMax = new Vector2(0.5f, 0f);
            track.pivot = new Vector2(0.5f, 0f);
            track.sizeDelta = new Vector2(w - pad * 2f, barHeight);
            track.anchoredPosition = new Vector2(0f, pad * 0.6f);

            _progressFill = UIFactory.CreatePanel("ProgressFill", track, Color.white);
            Stretch(_progressFill.rectTransform, 0f);
            _progressFill.type = Image.Type.Filled;
            _progressFill.fillMethod = Image.FillMethod.Horizontal;
            _progressFill.fillOrigin = (int)Image.OriginHorizontal.Left;
            _progressFill.fillAmount = 0f;

            Rebuild();
        }

        private void DestroyChild(string childName)
        {
            var stale = transform.Find(childName);
            if (stale != null) DestroyImmediate(stale.gameObject);
        }

        /// <summary>Carves the next horizontal band out of the card, top down.</summary>
        private RectTransform Block(string blockName, float width, float height, ref float cursor)
        {
            var rect = UIFactory.CreateRect(blockName, _root);
            rect.anchorMin = rect.anchorMax = new Vector2(0.5f, 0.5f);
            rect.pivot = new Vector2(0.5f, 1f);
            rect.sizeDelta = new Vector2(width, height);
            rect.anchoredPosition = new Vector2(0f, cursor);
            cursor -= height;
            return rect;
        }

        private Text TextBlock(string blockName, float width, float height, ref float cursor, int fontSize)
        {
            var rect = Block(blockName, width, height, ref cursor);
            var text = UIFactory.CreateText("Text", rect, "", fontSize);
            Stretch(text.rectTransform, 0f);

            // The square is see-through now, so the text sits on whatever the ground happens to
            // be - grass, dirt, tarmac. An outline is what keeps it readable on all of them.
            var outline = text.gameObject.AddComponent<Outline>();
            outline.effectColor = new Color(0.05f, 0.06f, 0.09f, 0.85f);
            outline.effectDistance = new Vector2(fontSize * 0.07f, fontSize * 0.07f);

            return text;
        }

        private static void Stretch(RectTransform rect, float inset)
        {
            rect.anchorMin = Vector2.zero;
            rect.anchorMax = Vector2.one;
            rect.offsetMin = new Vector2(inset, inset);
            rect.offsetMax = new Vector2(-inset, -inset);
        }

        /// <summary>Applies size and position. Cheap enough to call whenever they change.</summary>
        private void Rebuild()
        {
            if (_root == null) return;

            // 100 canvas pixels per world unit, then scaled back down, so the card is in metres.
            _root.sizeDelta = CardSize * 100f;
            _root.localScale = Vector3.one * 0.01f;
            _root.localPosition = Vector3.up * lift;
        }

        /// <summary>
        /// How far the card turns off the level grid towards the camera. 0 lies square with the
        /// world, 1 squares up with the screen.
        ///
        /// Squaring up with the screen makes the text perfectly level, and makes the card look
        /// like a UI panel pasted over the game: every building, field and road on screen is a
        /// slanted parallelogram, and an upright rectangle among them reads as something sitting
        /// in front of the world rather than lying in it. Following the grid instead costs a
        /// little legibility and buys the card its place on the ground.
        ///
        /// Zero: the square lies square with the world, like a bay marked out on the floor, and
        /// its text lies in the ground plane with it. This is the one number to change if the
        /// squares ever look wrong again.
        /// </summary>
        private const float ScreenAlign = 0f;

        /// <summary>
        /// Lays the card flat, angled along the ground.
        ///
        /// Unity composes Euler angles as Y then X, so this single rotation both flattens the
        /// card and sets the direction it runs in. Both yaws are read live - from the level root
        /// and from the camera - so re-angling either cannot silently leave every label askew.
        /// </summary>
        private void FaceCamera()
        {
            var camera = WorldUi.Camera;
            if (camera == null) return;

            float groundYaw = transform.eulerAngles.y;
            float yaw = groundYaw + Mathf.DeltaAngle(groundYaw, camera.transform.eulerAngles.y) * ScreenAlign;

            if (!float.IsNaN(_appliedYaw) && Mathf.Abs(Mathf.DeltaAngle(yaw, _appliedYaw)) < 0.05f) return;

            _appliedYaw = yaw;
            _root.rotation = Quaternion.Euler(90f, yaw, 0f);
        }

        /// <summary>
        /// Turns the whole square off when it is off screen. Disabling the canvas object takes
        /// it out of the UI rebuild and render passes entirely, which is the single biggest
        /// saving available: a full farm has thirty-five squares and the camera shows about six.
        /// </summary>
        private void SetVisible(bool visible)
        {
            if (_visible == visible) return;
            _visible = visible;

            if (_root != null) _root.gameObject.SetActive(visible);

            // Coming back on screen, re-apply everything: the station may have changed
            // completely while it was hidden.
            if (visible)
            {
                _hasAppliedColors = false;
                _lastFillAmount = -1f;
                _lastRawLabel = null;
                _labelTimer = 0f;
            }
        }

        private void LateUpdate()
        {
            if (_root == null || !_visible) return;
            FaceCamera();
        }

        private void Update()
        {
            if (_root == null || station == null) return;

            _visibilityTimer -= Time.deltaTime;
            if (_visibilityTimer <= 0f)
            {
                _visibilityTimer = VisibilityInterval;
                SetVisible(WorldUi.IsVisible(transform.position));
            }

            if (!_visible) return;

            bool occupied = station.IsOccupied;
            bool usable = station.IsOperational;
            float progress = station.Progress01;

            // Idle squares breathe gently to draw the eye. A square being used holds still,
            // because the progress bar is the thing the player should be reading.
            float targetScale = 1f;
            if (!occupied && usable)
                targetScale = 1f + Mathf.Sin(Time.time * pulseSpeed) * 0.5f * idlePulse + idlePulse * 0.5f;
            else if (occupied)
                targetScale = 1.03f;

            float previous = _scale;
            _scale = Mathf.Lerp(_scale, targetScale, Time.deltaTime * 9f);
            // Moving the canvas root re-transforms every child, so a square that has settled at
            // its resting size (an unusable one, or one being stood in) stops writing.
            if (Mathf.Abs(_scale - previous) > 0.0002f)
                _root.localScale = Vector3.one * 0.01f * _scale;

            Color baseColor = usable ? color : Color.Lerp(color, new Color(0.55f, 0.57f, 0.6f), 0.55f);

            // Dashed outline: soft when idle, bright and solid the moment you step in. This is
            // the single clearest signal that the player is standing in the right place.
            Color edge = new Color(
                Mathf.Lerp(baseColor.r, 1f, occupied ? 0.75f : 0.45f),
                Mathf.Lerp(baseColor.g, 1f, occupied ? 0.75f : 0.45f),
                Mathf.Lerp(baseColor.b, 1f, occupied ? 0.75f : 0.45f),
                occupied ? 1f : 0.8f);

            if (!_hasAppliedColors || !Same(_lastBorder, edge))
            {
                _lastBorder = edge;
                for (int i = 0; i < _edges.Length; i++) _edges[i].color = edge;
            }

            // A wash, not a panel: enough to lift the text off the grass, nowhere near enough to
            // hide what the square is painted on.
            Apply(_backdrop, ref _lastBackdrop, new Color(
                Mathf.Lerp(0.08f, baseColor.r, 0.55f),
                Mathf.Lerp(0.11f, baseColor.g, 0.55f),
                Mathf.Lerp(0.15f, baseColor.b, 0.55f),
                occupied ? 0.42f : 0.26f));

            Apply(_progressTrack, ref _lastTrackColor, new Color(1f, 1f, 1f, 0.16f));

            Apply(_progressFill, ref _lastFill, new Color(
                Mathf.Lerp(baseColor.r, 1f, 0.3f),
                Mathf.Lerp(baseColor.g, 1f, 0.3f),
                Mathf.Lerp(baseColor.b, 1f, 0.3f),
                0.95f));

            Apply(_label, ref _lastLabelColor, new Color(1f, 1f, 1f, usable ? 1f : 0.55f));

            _hasAppliedColors = true;

            // Changing fillAmount regenerates the image's geometry, so the eased value is
            // snapped to a step first. Forty steps is finer than the bar is wide on a phone,
            // and it means a bar that has finished moving stops costing anything at all.
            float eased = Mathf.Lerp(_lastFillAmount < 0f ? progress : _lastFillAmount,
                progress, Time.deltaTime * 12f);
            float stepped = Mathf.Round(eased * 40f) / 40f;
            if (!Mathf.Approximately(stepped, _lastFillAmount))
            {
                _lastFillAmount = stepped;
                _progressFill.fillAmount = stepped;
                // No progress means no bar at all, rather than an empty trough left behind.
                bool showBar = stepped > 0.001f;
                if (_progressTrack.gameObject.activeSelf != showBar)
                    _progressTrack.gameObject.SetActive(showBar);
            }

            _labelTimer -= Time.deltaTime;
            if (_labelTimer <= 0f)
            {
                _labelTimer = LabelInterval;
                RefreshText(usable);
            }
        }

        /// <summary>
        /// Everything driven by the station's own description of itself.
        ///
        /// Kept off the per-frame path on purpose: a till's icon reflects whoever is at the
        /// front of its queue, so reading it walks the queue, and the status strings are all
        /// built with interpolation. None of that needs doing sixty times a second.
        /// </summary>
        private void RefreshText(bool usable)
        {
            string raw = station.ActionLabel;
            if (raw != _lastRawLabel)
            {
                _lastRawLabel = raw;
                // Upper case here rather than in every level builder, and only when the source
                // string actually changed, so it costs nothing on the frames in between.
                _label.text = string.IsNullOrEmpty(raw) ? "" : raw.ToUpperInvariant();
            }

            string value = station.StatusValue;
            if (_value.text != value) _value.text = value;

            Apply(_value, ref _lastValueColor,
                new Color(1f, 0.93f, 0.66f, usable ? 0.95f : 0.5f));

            ItemDefinition item = station.IconItem;
            Sprite sprite = item != null ? IconFactory.For(item) : IconFactory.Action(station.Icon);

            if (sprite != _lastIconSprite)
            {
                _lastIconSprite = sprite;
                _iconImage.sprite = sprite;
                _iconImage.enabled = sprite != null;
            }

            // Drawn icons carry their own colours and are only ever dimmed. An item with no
            // artwork falls back to a plain disc, which has to be tinted to mean anything.
            bool needsTint = item != null && !IconFactory.HasArtwork(item);
            Color tint = needsTint ? item.color : Color.white;
            Apply(_iconImage, ref _lastIconColor,
                new Color(tint.r, tint.g, tint.b, usable ? 1f : 0.45f));
        }

        /// <summary>
        /// Writes a colour only when it has actually changed. Assigning the same colour still
        /// dirties the graphic and rebuilds its canvas, and an idle square assigns the same
        /// handful of colours every single frame.
        /// </summary>
        private void Apply(Graphic graphic, ref Color last, Color wanted)
        {
            if (graphic == null) return;
            if (_hasAppliedColors && Same(last, wanted)) return;

            last = wanted;
            graphic.color = wanted;
        }

        /// <summary>Equal to well below one step of an eight-bit colour channel.</summary>
        private static bool Same(Color a, Color b) =>
            Mathf.Abs(a.r - b.r) < 0.002f && Mathf.Abs(a.g - b.g) < 0.002f &&
            Mathf.Abs(a.b - b.b) < 0.002f && Mathf.Abs(a.a - b.a) < 0.002f;
    }
}
