using Tycoon.Stations;
using UnityEngine;
using UnityEngine.UI;

namespace Tycoon.UI
{
    /// <summary>
    /// The painted square on the ground that says "stand here".
    ///
    /// This is the main way the game talks to the player, so it has to do three things at a
    /// glance: say what the action is, make it obvious when you are actually inside it, and
    /// show how the action is going.
    ///
    /// Built as a world-space canvas laid flat rather than a textured quad, because the canvas
    /// route reuses the sprites and fonts generated by <see cref="UIFactory"/>, which are known
    /// to survive the Web build. Materials created from scratch at runtime render magenta in a
    /// URP player, which cost an hour to diagnose once already.
    /// </summary>
    public class InteractionSquare : MonoBehaviour
    {
        [Header("Source")]
        public StationBase station;

        [Header("Look")]
        public Vector2 size = new Vector2(2f, 2f);
        public Color color = new Color(0.35f, 0.8f, 1f);

        [Tooltip("Optional. When empty the square shows only its label.")]
        public Sprite icon;

        [Tooltip("Height above the ground. Just enough to avoid z-fighting.")]
        public float lift = 0.045f;

        [Header("Motion")]
        [Tooltip("How far the square swells while idle, inviting the player over.")]
        [Range(0f, 0.15f)] public float idlePulse = 0.045f;

        public float pulseSpeed = 2.1f;

        private RectTransform _root;
        private Image _border;
        private Image _backdrop;
        private Image _fill;
        private Image _iconImage;
        private Text _label;

        private float _scale = 1f;

        private void Awake() => Build();

        /// <summary>
        /// Called by the level builder. Deliberately stores data only and builds nothing:
        /// geometry created at edit time gets serialised into the scene, and then Awake builds
        /// a second copy at runtime. The saved one is left orphaned with nothing updating it,
        /// which shows up as a plain white rectangle sitting on top of the real square.
        /// </summary>
        public void Configure(StationBase owner, Vector2 squareSize, Color squareColor)
        {
            station = owner;
            size = squareSize;
            color = squareColor;
        }

        private void Build()
        {
            if (_root != null) return;

            // Reuse a leftover from an earlier session rather than stacking another one up.
            var existing = transform.Find("~Square");
            if (existing != null)
            {
                _root = (RectTransform)existing;
                _border = existing.Find("Border")?.GetComponent<Image>();
                _backdrop = existing.Find("Backdrop")?.GetComponent<Image>();
                _fill = existing.Find("Fill")?.GetComponent<Image>();
                _iconImage = existing.Find("Icon")?.GetComponent<Image>();
                _label = existing.Find("Label")?.GetComponent<Text>();
                if (_border != null && _backdrop != null && _fill != null && _label != null)
                {
                    Rebuild();
                    return;
                }
                DestroyImmediate(existing.gameObject);
                _root = null;
            }

            var go = new GameObject("~Square");
            // Never serialised into the scene - see Configure.
            go.hideFlags = HideFlags.DontSave;
            go.transform.SetParent(transform, false);
            // Flat on the ground. The parent already carries the level's 45 degree yaw, so the
            // square lines up with the level grid rather than with world axes.
            go.transform.localRotation = Quaternion.Euler(90f, 0f, 0f);

            var canvas = go.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.WorldSpace;

            _root = (RectTransform)go.transform;

            _border = UIFactory.CreatePanel("Border", _root, Color.white);
            Stretch(_border.rectTransform, 0f);

            _backdrop = UIFactory.CreatePanel("Backdrop", _root, Color.white);
            Stretch(_backdrop.rectTransform, 9f);

            _fill = UIFactory.CreatePanel("Fill", _root, Color.white);
            Stretch(_fill.rectTransform, 9f);
            _fill.type = Image.Type.Filled;
            _fill.fillMethod = Image.FillMethod.Horizontal;
            _fill.fillOrigin = (int)Image.OriginHorizontal.Left;
            _fill.fillAmount = 0f;

            var iconGo = UIFactory.CreateRect("Icon", _root);
            _iconImage = iconGo.gameObject.AddComponent<Image>();
            _iconImage.raycastTarget = false;
            iconGo.anchorMin = iconGo.anchorMax = new Vector2(0.5f, 0.68f);
            iconGo.pivot = new Vector2(0.5f, 0.5f);
            iconGo.sizeDelta = new Vector2(56f, 56f);
            _iconImage.enabled = false;

            _label = UIFactory.CreateText("Label", _root, "", 46);
            _label.fontStyle = FontStyle.Bold;
            Stretch(_label.rectTransform, 0f);

            Rebuild();
        }

        private static void Stretch(RectTransform rect, float inset)
        {
            rect.anchorMin = Vector2.zero;
            rect.anchorMax = Vector2.one;
            rect.offsetMin = new Vector2(inset, inset);
            rect.offsetMax = new Vector2(-inset, -inset);
        }

        /// <summary>Applies size, colour and label. Cheap enough to call whenever they change.</summary>
        private void Rebuild()
        {
            if (_root == null) return;

            // 100 canvas pixels per world unit, then scaled back down, so `size` is in metres.
            _root.sizeDelta = size * 100f;
            _root.localScale = Vector3.one * 0.01f;
            _root.localPosition = Vector3.up * lift;

            if (_iconImage != null)
            {
                _iconImage.sprite = icon;
                _iconImage.enabled = icon != null;
            }

            if (_label != null)
            {
                _label.text = station != null ? station.StatusText : "";
                // With an icon the text sits below it; without, it centres.
                _label.alignment = icon != null ? TextAnchor.LowerCenter : TextAnchor.MiddleCenter;
            }
        }

        private void Update()
        {
            if (_root == null || station == null) return;

            bool occupied = station.IsOccupied;
            bool usable = station.IsOperational;
            float progress = station.Progress01;

            // Idle squares breathe gently to draw the eye. A square being used holds still,
            // because the progress fill is the thing the player should be reading.
            float targetScale = 1f;
            if (!occupied && usable)
                targetScale = 1f + Mathf.Sin(Time.time * pulseSpeed) * 0.5f * idlePulse + idlePulse * 0.5f;
            else if (occupied)
                targetScale = 1.03f;

            _scale = Mathf.Lerp(_scale, targetScale, Time.deltaTime * 9f);
            _root.localScale = Vector3.one * 0.01f * _scale;

            Color baseColor = usable ? color : Color.Lerp(color, new Color(0.55f, 0.57f, 0.6f), 0.45f);

            // Border: thin and soft when idle, bright and solid the moment you step in. This is
            // the single clearest signal that the player is standing in the right place.
            _border.color = new Color(
                Mathf.Lerp(baseColor.r, 1f, occupied ? 0.55f : 0.15f),
                Mathf.Lerp(baseColor.g, 1f, occupied ? 0.55f : 0.15f),
                Mathf.Lerp(baseColor.b, 1f, occupied ? 0.55f : 0.15f),
                occupied ? 0.95f : 0.45f);

            _backdrop.color = new Color(baseColor.r, baseColor.g, baseColor.b, occupied ? 0.55f : 0.34f);

            _fill.color = new Color(
                Mathf.Lerp(baseColor.r, 1f, 0.35f),
                Mathf.Lerp(baseColor.g, 1f, 0.35f),
                Mathf.Lerp(baseColor.b, 1f, 0.35f),
                0.75f);
            _fill.fillAmount = Mathf.Lerp(_fill.fillAmount, progress, Time.deltaTime * 12f);

            _label.color = new Color(1f, 1f, 1f, usable ? 0.95f : 0.5f);

            string wanted = station.StatusText;
            if (_label.text != wanted) _label.text = wanted;
        }
    }
}
